CC = g++
INC = ./inc
OBJ = ./obj
SRC = ./src
BIN = ./bin
LFLAGS = -o
CFLAGS = -c -g -Wall -Werror
IFLAGS = l$(INC)

 all: $(OBJ)/app valgrind

 $(BIN)/app:$(OBJ)/employee.o
       $(CC) $(CFLAFS) $(BIN)/employee $(OBJ)/employee.o
       mv*.o $(OBJ)

$(OBJ)/employee.o:$(SRC)/employee.cpp
$(CC) $(CFLAGS) $(IFLAGS) $(SRC)/employee.cpp -o $(OBJ)/employee.o

 valgrind
       valgrind  --leak-check=full $(BIN)/app
       mv valgrind $(BIN)

 clean:
       rm -f $(OBJ)/*.o
       rm -f a.out
       rm -f $(BIN)/app
                                                                                                                                                                      ~            